//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZLMClaims.Resources.Languages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ZLMClaims.Resources.Languages.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        internal static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All claims.
        /// </summary>
        internal static string AllClaimsTitle {
            get {
                return ResourceManager.GetString("AllClaimsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All contracts.
        /// </summary>
        internal static string AllContractsTitle {
            get {
                return ResourceManager.GetString("AllContractsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All repair companies.
        /// </summary>
        internal static string AllRepairCompaniesTitle {
            get {
                return ResourceManager.GetString("AllRepairCompaniesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Annual policy premuim.
        /// </summary>
        internal static string AnnualPolicyPremium {
            get {
                return ResourceManager.GetString("AnnualPolicyPremium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application settings.
        /// </summary>
        internal static string ApplicationSettings {
            get {
                return ResourceManager.GetString("ApplicationSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        internal static string City {
            get {
                return ResourceManager.GetString("City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Claimform.
        /// </summary>
        internal static string ClaimFormPageTitle {
            get {
                return ResourceManager.GetString("ClaimFormPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1. Damage details.
        /// </summary>
        internal static string DamageDetails {
            get {
                return ResourceManager.GetString("DamageDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Damage free years.
        /// </summary>
        internal static string DamageFreeYears {
            get {
                return ResourceManager.GetString("DamageFreeYears", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2. Damage photos.
        /// </summary>
        internal static string DamagePhotos {
            get {
                return ResourceManager.GetString("DamagePhotos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3. Damage summary.
        /// </summary>
        internal static string DamageSummary {
            get {
                return ResourceManager.GetString("DamageSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What is the date of occurrence?.
        /// </summary>
        internal static string DateOfOccurrence {
            get {
                return ResourceManager.GetString("DateOfOccurrence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distance.
        /// </summary>
        internal static string Distance {
            get {
                return ResourceManager.GetString("Distance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enddate.
        /// </summary>
        internal static string EndDate {
            get {
                return ResourceManager.GetString("EndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        internal static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        internal static string Phone {
            get {
                return ResourceManager.GetString("Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous.
        /// </summary>
        internal static string Previous {
            get {
                return ResourceManager.GetString("Previous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What is damaged?.
        /// </summary>
        internal static string Q_WhatIsDamaged {
            get {
                return ResourceManager.GetString("Q_WhatIsDamaged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repair company.
        /// </summary>
        internal static string RepairCompanyTitle {
            get {
                return ResourceManager.GetString("RepairCompanyTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send.
        /// </summary>
        internal static string Send {
            get {
                return ResourceManager.GetString("Send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Startingdate.
        /// </summary>
        internal static string StartingDate {
            get {
                return ResourceManager.GetString("StartingDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Claim.
        /// </summary>
        internal static string TabItemClaim {
            get {
                return ResourceManager.GetString("TabItemClaim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contract.
        /// </summary>
        internal static string TabItemContract {
            get {
                return ResourceManager.GetString("TabItemContract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        internal static string TabItemHome {
            get {
                return ResourceManager.GetString("TabItemHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        internal static string TabItemProfile {
            get {
                return ResourceManager.GetString("TabItemProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repair.
        /// </summary>
        internal static string TabItemRepair {
            get {
                return ResourceManager.GetString("TabItemRepair", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cooperative.
        /// </summary>
        internal static string TabItemRepairCooperative {
            get {
                return ResourceManager.GetString("TabItemRepairCooperative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uncooperative.
        /// </summary>
        internal static string TabItemRepairUncooperative {
            get {
                return ResourceManager.GetString("TabItemRepairUncooperative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer number.
        /// </summary>
        internal static string UserId {
            get {
                return ResourceManager.GetString("UserId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        internal static string UserPageTitle {
            get {
                return ResourceManager.GetString("UserPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receive e-mail confirmation.
        /// </summary>
        internal static string UserSwitchEmailConfirmation {
            get {
                return ResourceManager.GetString("UserSwitchEmailConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switch to Dutch language.
        /// </summary>
        internal static string UserSwitchLanguage {
            get {
                return ResourceManager.GetString("UserSwitchLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switch theme.
        /// </summary>
        internal static string UserSwitchTheme {
            get {
                return ResourceManager.GetString("UserSwitchTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Website.
        /// </summary>
        internal static string Website {
            get {
                return ResourceManager.GetString("Website", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zipcode.
        /// </summary>
        internal static string ZipCode {
            get {
                return ResourceManager.GetString("ZipCode", resourceCulture);
            }
        }
    }
}
